<?php

namespace Database\Seeders;

use App\Models\Citizenship;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitizenshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Citizenship::insert([
            ['citizenship' => 'Afghan'],
            ['citizenship' => 'Albanian'],
            ['citizenship' => 'Algerian'],
            ['citizenship' => 'American'],
            ['citizenship' => 'Andorran'],
            ['citizenship' => 'Angolan'],
            ['citizenship' => 'Antiguan'],
            ['citizenship' => 'Argentine'],
            ['citizenship' => 'Armenian'],
            ['citizenship' => 'Australian'],
            ['citizenship' => 'Austrian'],
            ['citizenship' => 'Azerbaijani'],
            ['citizenship' => 'Bahamian'],
            ['citizenship' => 'Bahraini'],
            ['citizenship' => 'Bangladeshi'],
            ['citizenship' => 'Barbadian'],
            ['citizenship' => 'Belarusian'],
            ['citizenship' => 'Belgian'],
            ['citizenship' => 'Belizean'],
            ['citizenship' => 'Beninese'],
            ['citizenship' => 'Bhutanese'],
            ['citizenship' => 'Bolivian'],
            ['citizenship' => 'Bosnian'],
            ['citizenship' => 'Botswanan'],
            ['citizenship' => 'Brazilian'],
            ['citizenship' => 'Bruneian'],
            ['citizenship' => 'Bulgarian'],
            ['citizenship' => 'Burkinabe'],
            ['citizenship' => 'Burundian'],
            ['citizenship' => 'Cabo Verdean'],
            ['citizenship' => 'Cambodian'],
            ['citizenship' => 'Cameroonian'],
            ['citizenship' => 'Canadian'],
            ['citizenship' => 'Central African'],
            ['citizenship' => 'Chadian'],
            ['citizenship' => 'Chilean'],
            ['citizenship' => 'Chinese'],
            ['citizenship' => 'Colombian'],
            ['citizenship' => 'Comorian'],
            ['citizenship' => 'Congolese (Congo-Brazzaville)'],
            ['citizenship' => 'Costa Rican'],
            ['citizenship' => 'Croatian'],
            ['citizenship' => 'Cuban'],
            ['citizenship' => 'Cypriot'],
            ['citizenship' => 'Czech'],
            ['citizenship' => 'Danish'],
            ['citizenship' => 'Djiboutian'],
            ['citizenship' => 'Dominican'],
            ['citizenship' => 'Ecuadorian'],
            ['citizenship' => 'Egyptian'],
            ['citizenship' => 'El Salvadoran'],
            ['citizenship' => 'Equatorial Guinean'],
            ['citizenship' => 'Eritrean'],
            ['citizenship' => 'Estonian'],
            ['citizenship' => 'Eswatini'],
            ['citizenship' => 'Ethiopian'],
            ['citizenship' => 'Fijian'],
            ['citizenship' => 'Finnish'],
            ['citizenship' => 'French'],
            ['citizenship' => 'Gabonese'],
            ['citizenship' => 'Gambian'],
            ['citizenship' => 'Georgian'],
            ['citizenship' => 'German'],
            ['citizenship' => 'Ghanaian'],
            ['citizenship' => 'Greek'],
            ['citizenship' => 'Grenadian'],
            ['citizenship' => 'Guatemalan'],
            ['citizenship' => 'Guinean'],
            ['citizenship' => 'Guinea-Bissauan'],
            ['citizenship' => 'Guyanese'],
            ['citizenship' => 'Haitian'],
            ['citizenship' => 'Honduran'],
            ['citizenship' => 'Hungarian'],
            ['citizenship' => 'Icelander'],
            ['citizenship' => 'Indian'],
            ['citizenship' => 'Indonesian'],
            ['citizenship' => 'Iranian'],
            ['citizenship' => 'Iraqi'],
            ['citizenship' => 'Irish'],
            ['citizenship' => 'Israeli'],
            ['citizenship' => 'Italian'],
            ['citizenship' => 'Ivorian'],
            ['citizenship' => 'Jamaican'],
            ['citizenship' => 'Japanese'],
            ['citizenship' => 'Jordanian'],
            ['citizenship' => 'Kazakh'],
            ['citizenship' => 'Kenyan'],
            ['citizenship' => 'Kiribati'],
            ['citizenship' => 'North Korean'],
            ['citizenship' => 'South Korean'],
            ['citizenship' => 'Kosovar'],
            ['citizenship' => 'Kuwaiti'],
            ['citizenship' => 'Kyrgyz'],
            ['citizenship' => 'Laotian'],
            ['citizenship' => 'Latvian'],
            ['citizenship' => 'Lebanese'],
            ['citizenship' => 'Lesotho'],
            ['citizenship' => 'Liberian'],
            ['citizenship' => 'Libyan'],
            ['citizenship' => 'Liechtenstein'],
            ['citizenship' => 'Lithuanian'],
            ['citizenship' => 'Luxembourgish'],
            ['citizenship' => 'Malagasy'],
            ['citizenship' => 'Malawian'],
            ['citizenship' => 'Malaysian'],
            ['citizenship' => 'Maldivian'],
            ['citizenship' => 'Malian'],
            ['citizenship' => 'Maltese'],
            ['citizenship' => 'Marshallese'],
            ['citizenship' => 'Mauritanian'],
            ['citizenship' => 'Mauritian'],
            ['citizenship' => 'Mexican'],
            ['citizenship' => 'Micronesian'],
            ['citizenship' => 'Moldovan'],
            ['citizenship' => 'Monacan'],
            ['citizenship' => 'Mongolian'],
            ['citizenship' => 'Montenegrin'],
            ['citizenship' => 'Moroccan'],
            ['citizenship' => 'Mozambican'],
            ['citizenship' => 'Myanmar'],
            ['citizenship' => 'Namibian'],
            ['citizenship' => 'Nauruan'],
            ['citizenship' => 'Nepalese'],
            ['citizenship' => 'Dutch'],
            ['citizenship' => 'New Zealander'],
            ['citizenship' => 'Nicaraguan'],
            ['citizenship' => 'Nigerien'],
            ['citizenship' => 'Nigerian'],
            ['citizenship' => 'North Macedonian'],
            ['citizenship' => 'Norwegian'],
            ['citizenship' => 'Omani'],
            ['citizenship' => 'Pakistani'],
            ['citizenship' => 'Palauan'],
            ['citizenship' => 'Palestinian'],
            ['citizenship' => 'Panamanian'],
            ['citizenship' => 'Papua New Guinean'],
            ['citizenship' => 'Paraguayan'],
            ['citizenship' => 'Peruvian'],
            ['citizenship' => 'Filipino'],
            ['citizenship' => 'Polish'],
            ['citizenship' => 'Portuguese'],
            ['citizenship' => 'Qatari'],
            ['citizenship' => 'Romanian'],
            ['citizenship' => 'Russian'],
            ['citizenship' => 'Rwandan'],
            ['citizenship' => 'Kittitian'],
            ['citizenship' => 'Saint Lucian'],
            ['citizenship' => 'Saint Vincentian'],
            ['citizenship' => 'Samoan'],
            ['citizenship' => 'San Marinese'],
            ['citizenship' => 'Sao Tomean'],
            ['citizenship' => 'Saudi'],
            ['citizenship' => 'Senegalese'],
            ['citizenship' => 'Serbian'],
            ['citizenship' => 'Seychellois'],
            ['citizenship' => 'Sierra Leonean'],
            ['citizenship' => 'Singaporean'],
            ['citizenship' => 'Slovak'],
            ['citizenship' => 'Slovenian'],
            ['citizenship' => 'Solomon Islander'],
            ['citizenship' => 'Somali'],
            ['citizenship' => 'South African'],
            ['citizenship' => 'South Sudanese'],
            ['citizenship' => 'Spanish'],
            ['citizenship' => 'Sri Lankan'],
            ['citizenship' => 'Sudanese'],
            ['citizenship' => 'Surinamese'],
            ['citizenship' => 'Swedish'],
            ['citizenship' => 'Swiss'],
            ['citizenship' => 'Syrian'],
            ['citizenship' => 'Taiwanese'],
            ['citizenship' => 'Tajik'],
            ['citizenship' => 'Tanzanian'],
            ['citizenship' => 'Thai'],
        ]);
    }
}
